README.md, lam4-parser/examples/open_sums.l4, lam4-parser/package.json, lam4-parser/src/language/lam4.langium
Augmented Lam4 langium grammar with:
* simple math, bool ops 
* predicate decl
Docs (README + comments in Langium grammar file):
* Add misc thoughts on visualization and explanation
* Add thoughts on how important it is to support mixfix operators
* Add links re IDE protocol / synchronizing state between, e.g., a textual editor and a diagrammatic one
Deps:
* upgrade vitest
=> Augment grammar with simple math, bool ops and predicate decl + Docs

lam4-parser/src/language/lam4.langium, lam4-parser/src/language/type-system/infer.ts, lam4-parser/src/language/type-system/type-tags.ts
1. Improve type annotations grammar --- make it a tree instead of a sequence
2. adapt type checker accordingly
3. Clean up type tags code / rationalize the function-like tags interfaces
Closes #10
=> Improve type annotations grammar --- make it a tree instead of a sequence --- and adapt type checker accordingly

lam4-parser/src/language/lam4.langium
TODO: Will need to do more to support things like `§10(1)(a)`
Partially tackles #34
=> Adds partial support for original rule references / citations like `§10`

lam4-backend/app/Main.hs, lam4-backend/lam4-backend.cabal, lam4-backend/src/Base.hs, lam4-backend/src/Base/Aeson.hs, lam4-backend/src/Base/AesonCombinators.hs, lam4-backend/src/Base/IntMap.hs, lam4-backend/src/Base/Plated.hs, lam4-backend/src/Lam4/Expr/ConcreteSyntax.hs, lam4-backend/src/Lam4/Expr/Name.hs, lam4-backend/src/Lam4/Expr/Parser.hs, lam4-backend/src/Lam4/Parser/Monad.hs, lam4-backend/src/Lam4/Parser/Type.hs, lam4-frontend/src/language/lam4-json-serializer.ts, lam4-frontend/src/language/lam4-module.ts, lam4-frontend/src/language/lam4.langium
The parser I'd written in the Langium framework exports a serialized-to-json version of the syntax (see, e..g, `node ./bin/cli toMinimalAst examples/chained_record_deref.l4`, from the `lam4/lam4-frontend` dir). This PR reads in that json into the Haskell backend.
Closes #44 .
The next steps:
* The grammar / concrete syntax so far is pretty simple --- will be adding constructs like `WHERE` in the near future, along with desugaring
* In particular, I will probably add records in (there's some subtle differences between records and relations)
* Add tests
* The Main.hs offers a simple, 'internal' CLI for this parser; this will be wired up to an evaluator in the near future
* Add a 'public', more stable CLI for `lam4`, in the root dir
Mostly tagging reviewers as an fyi --- not sure that this …
=> Add a backend parser that parses in the ('minimal ast' version of the) concrete syntax json from Langium parser (closes #44)

lam4-backend/src/Lam4/Expr/ConcreteSyntax.hs, lam4-backend/src/Lam4/Expr/Parser.hs
@inariksit : Here's the grammar --- ConcreteSyntax.hs -- I had promised to send you, as preparation for experiments on 'rendering' in natural language! Note that it's not currently in sync with the stuff in the Langium lam4-frontend -- the frontend grammar and type checker haven't yet been updated with the constructs I just added. 
We can talk more later about more detailed desiderata for the rendering. My rough inclination right now would be to borrow ideas from ACE and what John Camilleri has done, except maybe tweak things to sound more like what one would see in contracts / legal texts (see Tina Stark's and Ken Adams' textbooks).
The expression language fragment of this concrete syntax is a superset of the main branch L4 syntax (i.e., the latter is a subtype of the former), so it …
=> Augment concrete syntax with (i) records, record projection and (ii) very WIP sketch of normative clauses

lam4-backend/src/Lam4/Expr/ConcreteSyntax.hs, lam4-backend/src/Lam4/Expr/Parser.hs
I'm trying to minimize differences when it comes to areas where Lam4's semantics coincides with that of Simala, so as to minimize unnecessary work when adapting, e.g., work on tooling that was done with Lam4 to `dsl`-L4.
If `dsl`-L4's concrete syntax ends up diverging in its naming conventions from Simala's, I'll tweak Lam4 concrete syntax accordingly, where possible.
=> Tweak Lam4 concrete syntax to avoid unnecessary or unintentional differences from Simala syntax / semantics

docs/proposal_normative_constructs_aug26_2024.md, lam4-backend/lam4-backend.cabal, lam4-backend/src/Lam4/Expr/AbstractSyntax.hs, lam4-backend/src/Lam4/Expr/CommonSyntax.hs, lam4-backend/src/Lam4/Expr/ConcreteSyntax.hs, lam4-backend/src/Lam4/Expr/Name.hs, lam4-backend/src/Lam4/Expr/Parser.hs
- Clean up concrete syntax: 
- add block of statements as variant to Expr; 
- make Let a Let Decl; inline deontic stuff). 
- Remove TopLevelElement
- Change `Parser.hs` accordingly
- Fix derivations for symbolic types for AST
- Proposal: Fix formatting issue
=> Grammar, Concrete Syntax (and Parser.hs) tweaks

README.md, lam4-backend/README.md, lam4-frontend/examples/chained_record_deref.l4, lam4-frontend/examples/simple_atomic_actions_borrower_debt.l4, lam4-frontend/examples/simple_join_or_record_field_deref.l4, lam4-frontend/package.json, lam4-frontend/src/language/lam4-lang-utils.ts, lam4-frontend/src/language/lam4-scope.ts, lam4-frontend/src/language/lam4.langium, lam4-frontend/src/language/type-system/infer.ts, lam4-frontend/src/language/type-system/type-tags.ts
- Add basic support for records in type checker / adapt the old Sig/Join stuff to Record/Project (but keep basic support for SigDecl)
- Add `then` separator for sequential composition of actions
=> Add basic support for records in type checker; add `then` separator for sequential composition of actions

lam4-backend/src/Lam4/Expr/AbstractSyntax.hs, lam4-backend/src/Lam4/Expr/CommonSyntax.hs, lam4-backend/src/Lam4/Expr/ConcreteSyntax.hs, lam4-backend/src/Lam4/Expr/Parser.hs, lam4-backend/src/Lam4/Parser/Monad.hs, lam4-backend/src/Lam4/Parser/Type.hs, lam4-frontend/src/language/lam4.langium, lam4-frontend/src/language/type-system/type-tags.ts
The biggest class of things right now that is in the Langium grammar but not yet supported in the backend parser is the normative stuff.
The Haskell backend parser has *not* been tested thoroughly -- that's a big short-term TODO as well
=> Add record decls to common syntax; implement parser for that and record exprs and projection and some other misc decls in backend parser

lam4-frontend/src/language/lam4-module.ts
=> Langium frontend: Add ValueConverter that trims backticks from backticked IDs and "--" and leading spaces from single line annotation

.gitignore, examples/PostfixPredicateApplication.l4, examples/infix_pred_app.l4, examples/not.l4, examples/simple_join_or_record_field_deref.l4, lam4-backend/lam4-backend.cabal, lam4-backend/src/Lam4/Expr/CommonSyntax.hs, lam4-backend/src/Lam4/Expr/ConcreteSyntax.hs, lam4-backend/src/Lam4/Expr/Parser.hs, lam4-backend/src/Lam4/Expr/SymEvalAST.hs, lam4-backend/src/Lam4/Expr/ToConcreteEvalAST.hs, lam4-backend/src/Lam4/Expr/ToSimala.hs, lam4-cli/app/Main.hs, lam4-frontend/src/language/lam4.langium, lam4-frontend/src/language/type-system/infer.ts
1. Refactor predicate and action application in the Langium grammar (streamlined some of the pred app; distinguish between postfix and infix pred app)
2. Update backend parser accordingly, though still desugaring to one PredApp construct
3. Add function type to backend concrete syntax
4. Update .gitignore to exclude generated files
5. Misc clean ups
@inariksit I haven't added infix pred app to the backend ConcreteSyntax (just desugaring it right now to PredApp) --- I'm deferring that for now because getting the web-based IDE up etc is higher priority
=> Improve pred decl app

examples/infix_pred_app.l4, lam4-frontend/src/language/lam4.langium
TODO: Add a validator to warn user if they miss one of the params, e.g.
```
GIVEN (some_person: Person 
another_person: Person)
DECIDE some_person `has helped`
IF True
```
(This is purely stylistic, but could still be confusing to a reader; hence the need for a validator)
=> Langium Grammar: Allow for an 'infix' predicate definition style. This is purely cosmetic / stylistic.

lam4-frontend/src/language/lam4.langium
Had been on the fence about this because this doesn't always look good, but backticked param names seem like they might come up in the RF usecase.
Will also need to change the genitive syntax to make it look nicer, since right now we might have stuff like
```
`some applicant``s` publications < 2
```
=> Langium Grammar: Allow param names to be backticked ID as well.

lam4-frontend/package.json
Fixes issue where syntax highlighting might not show up even when generated VSCode extension is used.
=> `package.json`: Add `syntaxes` to `files`

docs/proposal_normative_constructs_aug26_2024.md, examples/PostfixPredicateApplication.l4, examples/chained_record_deref.l4, examples/not.l4, examples/predicate_and_givens_variations.l4, examples/simple_join_or_record_field_deref.l4, lam4-backend/src/Lam4/Expr/ConcreteSyntax.hs, lam4-frontend/src/language/lam4.langium, lam4-frontend/src/language/type-system/infer.ts
The only remaining issue is that the auto-inferred syntax highlighting may not be very nice now -- may need to adjust that.
There may also be subtle precedence issues with the terminals that I haven't flushed out. @inariksit has agreed to give this a quick look; I'm going to just merge it in first, though, because even if there are precedence issues, fixing them should be easy.
=> Langium Grammar: Improve genitive construct -- now `'s` instead of ``s``.

examples/PostfixPredicateApplication.l4, examples/arithmetic.l4, examples/atomic_actions_transitive_if_then_infringed.l4, examples/chained_record_deref.l4, examples/foldr_length.l4, examples/function_application.l4, examples/infix_pred_app.l4, examples/life_assured_predicate_fun_decl.l4, examples/lottery.l4, examples/not.l4, examples/predicate_and_givens_variations.l4, examples/simple_atomic_actions_borrower_debt.l4, examples/simple_atomic_actions_with_party_sigs.l4, examples/simple_join_or_record_field_deref.l4, examples/simple_life_assured.l4, lam4-frontend/src/language/lam4.langium
List Ops parsing haven't been added to backend yet --- that's for the next PR
=> Add list ops to Langium grammar; move away from braces to explicit `END` delimiter; add delimiter for function declarations to avoid clashes

lam4-backend/src/Lam4/Expr/ConcreteSyntax.hs, scripts/cabal-run-examples.sh
1. Refactor `exprSubexprsVL` to avoid risk of inadvertently missing cases
2. Add temp useful helper dev script for batch cabal running examples (just do `./scripts/cabal-run-examples.sh`)
=> Quick refactor / clean up

lam4-frontend/src/language/lam4.langium
I think I had wanted to impose some restrictions in the past on where backticked IDs could be used, for cosmetic reasons, but the RF usecase is showing me that that doesn't make sense.
=> Allow RecordDecl, FunDecl, SigDecl names to be backticked ID

cabal.project, examples/chained_record_deref.l4, examples/let.l4, examples/let2_shadowing.l4, examples/let_backticked_id.l4, examples/nested_let_shadowing.l4, lam4-backend/src/Lam4/Expr/Parser.hs, lam4-frontend/src/language/lam4.langium, scripts/cabal-run-examples.sh
Fixes (i) var bindings in Let Expr and (ii) nesting Let expressions in surface syntax, e.g.
```lam4
LET {  
z = 2,
x = 1
} IN { 
LET { x = 100} IN { x }
}
```
I did, however, run into the following issue; seems to be due to `let rec` vs `let`:
Lam4 input program
```lam4
@REPORT 
LET { 
x = 1,
y = LET { x = 10 } IN { x } } 
IN { 
x + y * y 
}
```
The parsed-into-backend Lam4 concrete syntax; the shadowing was correctly picked up on
```
Eval
(Let
(NonRec "x" _1 (Lit (IntLit 1)))
(Let
(Rec "y" _2 (Let (NonRec "x" _3 (Lit (IntLit 10))) (Var "x" _3)))
(BinExpr
Plus (Var "x" _1) (BinExpr Mult (Var "y" _2) (Var "y" _2)))))
```
Simala exprs and eval
```
#eval let opaque x_1 = 1 in letrec opaque y_2 = let opaque x_3 = 10 in x_3 in x_1 + y_2 * y_2
"-------------------------------"
x_1 = 1
y_2 = 10 …
```
=> Langium grammar: Fix some Let issues: var bindings in `LetExpr` and nesting Let

examples/decimal.l4, examples/fractionals.l4, examples/unary_minus_integer.l4, lam4-backend/src/Base/Text.hs, lam4-backend/src/Lam4/Expr/ConcreteSyntax.hs, lam4-backend/src/Lam4/Expr/Parser.hs, lam4-backend/src/Lam4/Expr/ToSimala.hs, lam4-frontend/src/language/lam4.langium
1. Add fractionals / decimalliteral
2. ToSimala: Translate unary minus literal patterns to `-1 * x`, accounting for Int vs Frac literals
This obviously won't be enough for applications of UnaryMinus to a non-literal (since can't tell if it's an Int or Frac). For those, will need a `negate` function. The `negate` function can be made a std lib function if time permits.
Examples:
```
DEFINE fractional = 0.5 * 0.5
DEFINE negative = -0.3
DEFINE squared = negative * negative
@REPORT fractional
// for next PR
// @REPORT floor(fractional);
// @REPORT ceiling(fractional);
// @REPORT fractional * fromInt(2);
@REPORT negative
@REPORT squared
```
outputs as
```
❯ cabal run lam4-cli -- examples/fractionals.l4
"------- CST -------------"
[ NonRec
"fractional"
_1
(BinExpr Mult (Lit (FracLit 0.5)) (Lit …
```
=> Refactor Integer, add Fractionals / DecimalLiteral. 

examples/chained_record_deref.l4, lam4-frontend/src/language/lam4.langium
`chained_record_deref.l4` looks like this for me now
@johsi-k could you help me check if it looks ok when you build an extension and look at that file too?
This doesn't yet fix all auto-generated syntax highlighting issues: e.g., it's not great that `is` is highlighted in the following. But at least it seems to fix the most glaring syntax highlighting issue.
=> Fix the auto-inferred / auto-generated genitive syntax highlighting by removing single quotes from `STRING` terminal

examples/functions_with_no_type_annots.l4, lam4-backend/src/Lam4/Expr/Parser.hs, lam4-frontend/src/language/lam4.langium
1. Langium Grammar: Make type annots optional
2. Fix: Make parsing of record expr labels consistent with demo hack
=> Make type annots optional; Fix: Make parsing of record expr labels consistent with demo hack

experiments/ide-interfaces/l4extensionprototype/package.json, experiments/ide-interfaces/l4extensionprototype/pnpm-lock.yaml, experiments/ide-interfaces/l4extensionprototype/src/interfaces/README.md, experiments/ide-interfaces/l4extensionprototype/src/interfaces/decisionLogicIRNode.ts, experiments/ide-interfaces/l4extensionprototype/src/interfaces/visualizeProgramRequest.ts
1. Refactor: Standardize the annotation mechanism for IRNode and make it more extensible / less restrictive.
2. Add more docs, esp. re design intent.
3. Add link to useful-looking resource for LSP interfaces
=> Refactor interfaces and add more docs

cabal.project, lam4-backend/lam4-backend.cabal
Avoid 'allow-newer: *' and 'allow-older: *' as this is easily affected by the index-state of the respective user, causing build failures that aren't trivial to resolve.
=> Explicitly set `allow-newer` for gf
